name: CI/CD

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test And Upload Test Coverage To Codacy
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test code
      run: |
        pip install coverage
        coverage run --source=. -m unittest discover -s tests -p '*_test.py'
        coverage xml
        export CODACY_PROJECT_TOKEN="$CODACY_API_TOKEN"
        bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r coverage.xml
      env: 
        CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
    - name: Lint code with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

